import * as THREE from 'three';
import { OBJExporter } from 'three/addons/exporters/OBJExporter.js';
import JSZip from 'jszip';

export interface ObjExportResult {
  zipBlob: Blob;
  objText: string;
  mtlText: string;
}

/**
 * Generates an OBJ file with preserved object/group names,
 * creates a companion .mtl material library, and bundles them into a ZIP.
 */
export async function exportObjWithMtl(
  root: THREE.Object3D,
  baseFilename: string = 'model'
): Promise<Blob> {
  const exporter = new OBJExporter();
  let rawObj = exporter.parse(root);

  // Generate companion MTL file
  const mtlFilename = `${baseFilename}.mtl`;
  const mtlContent = generateMtl(root);

  // Inject mtllib header into OBJ if not present
  if (!rawObj.includes('mtllib ')) {
    rawObj = `# Procedural Three.js Exporter OBJ\nmtllib ${mtlFilename}\n\n` + rawObj;
  }

  // Bundle into ZIP
  const zip = new JSZip();
  zip.file(`${baseFilename}.obj`, rawObj);
  zip.file(mtlFilename, mtlContent);

  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return zipBlob;
}

/**
 * Traverses root to extract materials and builds standard Wavefront MTL content.
 */
function generateMtl(root: THREE.Object3D): string {
  const lines: string[] = [
    `# Wavefront MTL file generated by Three.js Local Exporter`,
    `# Material Count`,
  ];

  const processedMaterials = new Set<string>();

  root.traverse((obj) => {
    if ((obj as THREE.Mesh).isMesh) {
      const mesh = obj as THREE.Mesh;
      const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material];

      mats.forEach((mat) => {
        if (!mat || processedMaterials.has(mat.name || mat.uuid)) return;
        const matName = sanitizeMtlName(mat.name || `material_${mat.id}`);
        processedMaterials.add(matName);

        const color = (mat as unknown as { color?: THREE.Color }).color || new THREE.Color(0.8, 0.8, 0.8);
        const opacity = mat.opacity !== undefined ? mat.opacity : 1.0;
        const roughness = (mat as unknown as { roughness?: number }).roughness ?? 0.5;
        const metalness = (mat as unknown as { metalness?: number }).metalness ?? 0.1;

        // Specular exponent approximation from roughness
        const shininess = Math.max(1, Math.round((1 - roughness) * 100));

        lines.push('');
        lines.push(`newmtl ${matName}`);
        lines.push(`Ka 0.1 0.1 0.1`);
        lines.push(`Kd ${color.r.toFixed(4)} ${color.g.toFixed(4)} ${color.b.toFixed(4)}`);
        lines.push(`Ks ${metalness.toFixed(4)} ${metalness.toFixed(4)} ${metalness.toFixed(4)}`);
        lines.push(`Ns ${shininess}`);
        lines.push(`d ${opacity.toFixed(4)}`);
        lines.push(`illum 2`);
      });
    }
  });

  return lines.join('\n');
}

function sanitizeMtlName(name: string): string {
  return name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_\-\.]/g, '');
}
